#!/usr/bin/env bash
# =============================================================================
# setup/05_get_upstream.sh — extract the REAL pyperformance benchmark kernels.
#
# WHY THIS EXISTS
# ---------------
# bench/bm_raytrace.py and bench/bm_nbody.py are independently written
# stand-ins. The assignment asks for the approved pyperformance benchmarks, and
# an external review flagged substitution as the single largest compliance risk.
#
# This script copies the genuine kernels VERBATIM out of the installed
# pyperformance package into upstream/, and records provenance (package version
# + sha256 of each file) so a result set can be traced to an exact source.
#
# Nothing is modified. bench/bm_*_upstream.py import these files unchanged and
# add only a CLI.
#
# Run AFTER ./setup/04_make_venv.sh. Idempotent.
# =============================================================================
set -Eeuo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=../config/bench.env
REPO_ROOT="$ROOT" source "$ROOT/config/bench.env"

DEST="$ROOT/upstream"
mkdir -p "$DEST"

[[ -f "$VENV_DIR/bin/activate" ]] || {
  echo "!! venv missing at $VENV_DIR — run ./setup/04_make_venv.sh first" >&2
  exit 1; }

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

PP_DIR="$(python -c 'import pyperformance,os;print(os.path.dirname(pyperformance.__file__))' 2>/dev/null)" || {
  echo "!! pyperformance not importable in $VENV_DIR" >&2; exit 1; }
PP_VER="$(python -c 'import pyperformance;print(pyperformance.__version__)' 2>/dev/null || echo unknown)"
PY_VER="$(python -VV 2>&1 | tr '\n' ' ')"

echo "==> pyperformance $PP_VER"
echo "    $PP_DIR"

copied=0
for b in raytrace nbody; do
  SRC="$PP_DIR/data-files/benchmarks/bm_$b/run_benchmark.py"
  if [[ ! -f "$SRC" ]]; then
    # Layout has moved between releases; search as a fallback.
    SRC="$(find "$PP_DIR" -path "*bm_$b*" -name 'run_benchmark.py' 2>/dev/null | head -1)"
  fi
  if [[ -n "$SRC" && -f "$SRC" ]]; then
    cp "$SRC" "$DEST/bm_${b}_upstream.py"
    printf '    %-10s %s lines  sha256 %s\n' "$b" \
      "$(wc -l < "$SRC" | tr -d ' ')" \
      "$(sha256sum "$SRC" 2>/dev/null | cut -c1-16 || shasum -a 256 "$SRC" | cut -c1-16)"
    copied=$((copied+1))
  else
    echo "    $b: NOT FOUND under $PP_DIR" >&2
  fi
done

{
  echo "# upstream/ provenance"
  echo "# Generated by setup/05_get_upstream.sh — do not edit by hand."
  echo
  echo "extracted_utc:        $(date -u +%FT%TZ)"
  echo "pyperformance:        $PP_VER"
  echo "pyperformance_path:   $PP_DIR"
  echo "python:               $PY_VER"
  echo "host:                 $(uname -srm)"
  echo
  echo "# sha256 of each extracted file, as copied (unmodified):"
  (cd "$DEST" && { sha256sum ./*.py 2>/dev/null || shasum -a 256 ./*.py; })
  echo
  echo "# These files are third-party code redistributed under their original"
  echo "# licences (MIT for the raytracer; Computer Language Benchmarks Game"
  echo "# for nbody). Author attribution is preserved in each file's header."
} > "$DEST/PROVENANCE.txt"

deactivate 2>/dev/null || true

echo
echo "==> wrote $copied file(s) + PROVENANCE.txt to upstream/"
cat "$DEST/PROVENANCE.txt" | sed -n '1,14p' | sed 's/^/    /'

echo
echo "==> verifying the wrappers can drive them"
for b in raytrace nbody; do
  W="$ROOT/bench/bm_${b}_upstream.py"
  [[ -f "$W" ]] || { echo "    $b: wrapper missing"; continue; }
  printf '    %-10s ' "$b"
  if [[ "$b" == "nbody" ]]; then
    "$PY_REL" "$W" --mode verify --iterations 2000 >/dev/null 2>&1 \
      && echo "verify OK" || echo "verify FAILED"
  else
    "$PY_REL" "$W" --mode raw --loops 1 --width 24 --height 24 >/dev/null 2>&1 \
      && echo "runs OK" || echo "FAILED"
  fi
done

echo
echo "next: USE_UPSTREAM=1 ./script_raytrace.sh --variant baseline"
